apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow-container
        image: ghcr.io/mlflow/mlflow:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: mlflow-config
        command: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]