apiVersion: apps/v1
kind: Deployment
metadata:
  name: ifs-serving-deployment
  labels:
    app: ifs-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ifs-serving
  template:
    metadata:
      labels:
        app: ifs-serving
    spec:
      containers:
      - name: ifs-serving-container
        image: carlosrosado/serving-ifs-image:latest
        ports:
        - containerPort: 8001 # Application port
        - containerPort: 9091 # Prometheus metrics port
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow:5000" # MLflow Tracking URI
        - name: MODEL_NAME
          value: "ifs_Random_Forest"
        - name: OPENAPI_FILE_PATH
          value: "/app/app/prediction-openapi.yaml"
        envFrom:
        - configMapRef:
            name: mlflow-config
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9091
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9091
          initialDelaySeconds: 30
          periodSeconds: 20